README.md

@csharrison Could you review this change.
This closes #6, closes #7, closes #8, closes #9, closes #14, closes #15.

Change to using a Fetch API for the browser and add public metadata.

---

README.md

Update origins to use *.example.

---

README.md

Removes SRR format being specified in the core protocol and adds a versioning extension.

Add changes for TrustTokenV2 design.

---

README.md

This brings the explainer in line with the construction in ISSUER_PROTOCOL.md.
This fixes #18.

Update explainer private metadata reference.

---

ISSUER_PROTOCOL.md
README.md

Add multiple issuer support for send-redemption-record.

---

ISSUER_PROTOCOL.md

Expand on V3 version history to explicitly mention multiple issuers

Elaborate V3 version history

---

spec.bs

(nothing here is substantive, just for readability.)

Grammatical tweaks

---

spec.bs

This is fixing some low-hanging fruit in the query APIs, with a bunch of TODOs for more thorough specification.

Initial cleanup of query APIs

---

spec.bs

OK, this should be ready for review now - Fixes #144.
I'm basing the definitions here on me skimming the spec and reading some code comments - might make sense to just land it, and either @dvorak42 or @aykutbulut can make some edits to make it correct. Or we can do that in review.

Issue #144 - Define HTTP headers

---

spec.bs

Some very WIP work on better integrating (monkeypatching) this with Fetch

WIP Fetch integration

---

spec.bs

Add type to hasPrivateTokens/hasRedemptionRecord

---

spec.bs

Replace "blinded" with "masked" and add note

---

spec.bs

Define how to check whether we've hit a redemption limit.

---

spec.bs

This closes #150.
***
<a href="https://pr-preview.s3.amazonaws.com/cfredric/trust-token-api/pull/169.html" title="Last updated on Feb 17, 2023, 3:20 PM UTC (b533f1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/169/7ac85d4...cfredric:b533f1d.html" title="Last updated on Feb 17, 2023, 3:20 PM UTC (b533f1d)">Diff</a>

Define redemption records

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/174.html" title="Last updated on Feb 17, 2023, 4:12 PM UTC (d18016a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/174/5f1bc15...d18016a.html" title="Last updated on Feb 17, 2023, 4:12 PM UTC (d18016a)">Diff</a>

Add recommendations for implementation-defined values.

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/SamuelSchlesinger/trust-token-api/pull/175.html" title="Last updated on Feb 17, 2023, 4:28 PM UTC (030553a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/175/5f1bc15...SamuelSchlesinger:030553a.html" title="Last updated on Feb 17, 2023, 4:28 PM UTC (030553a)">Diff</a>

Added some English to the definitions section

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/178.html" title="Last updated on Feb 17, 2023, 4:34 PM UTC (23635d5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/178/f178b5d...23635d5.html" title="Last updated on Feb 17, 2023, 4:34 PM UTC (23635d5)">Diff</a>

Add algorithms for associating issuers to top-level origins.

---

spec.bs

Fixes #177
***
<a href="https://pr-preview.s3.amazonaws.com/aakallam/trust-token-api/pull/181.html" title="Last updated on Feb 17, 2023, 4:46 PM UTC (9249e21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/181/e4fb492...aakallam:9249e21.html" title="Last updated on Feb 17, 2023, 4:46 PM UTC (9249e21)">Diff</a>

Fix some grammatical errors in the Background section.

---

spec.bs

Fixes #154
***
<a href="https://pr-preview.s3.amazonaws.com/krgovind/trust-token-api/pull/180.html" title="Last updated on Feb 17, 2023, 5:01 PM UTC (a073c6a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/180/952a0c4...krgovind:a073c6a.html" title="Last updated on Feb 17, 2023, 5:01 PM UTC (a073c6a)">Diff</a>

Update normative references

---

spec.bs

Fixes #161
***
<a href="https://pr-preview.s3.amazonaws.com/ryankalla/trust-token-api/pull/171.html" title="Last updated on Feb 17, 2023, 4:49 PM UTC (36d986e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/171/f178b5d...ryankalla:36d986e.html" title="Last updated on Feb 17, 2023, 4:49 PM UTC (36d986e)">Diff</a>

Append structured headers using set a structured field value

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/krgovind/trust-token-api/pull/192.html" title="Last updated on Feb 17, 2023, 7:34 PM UTC (a6b5ad7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/192/8e652b1...krgovind:a6b5ad7.html" title="Last updated on Feb 17, 2023, 7:34 PM UTC (a6b5ad7)">Diff</a>

Link to GH tracking issues

---

.github/workflows/auto-publish.yml

I think the underlying issue was fixed.

Un-skip validating markup

---

spec.bs

Fixes #187.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/194.html" title="Last updated on Feb 22, 2023, 4:41 PM UTC (6f415f2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/194/da9e4b3...6f415f2.html" title="Last updated on Feb 22, 2023, 4:41 PM UTC (6f415f2)">Diff</a>

Add description of looking up key commitments.

---

spec.bs

Fixes #199
***
<a href="https://pr-preview.s3.amazonaws.com/johannhof/trust-token-api/pull/201.html" title="Last updated on Feb 24, 2023, 12:05 PM UTC (e351c0a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/201/7f49956...johannhof:e351c0a.html" title="Last updated on Feb 24, 2023, 12:05 PM UTC (e351c0a)">Diff</a>

Set cache mode to bypass cache

---

spec.bs

(I would merge this after #204, because it's probably going to get sad about the missing request disambiguation).
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/205.html" title="Last updated on Feb 27, 2023, 6:02 PM UTC (c6c79bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/205/c7d65b1...c6c79bf.html" title="Last updated on Feb 27, 2023, 6:02 PM UTC (c6c79bf)">Diff</a>

Some metadata updates, ids for examples, editorial changes

---

spec.bs

Fixes #196 and #197.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/207.html" title="Last updated on Mar 2, 2023, 2:45 PM UTC (e1c3eaf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/207/c7d65b1...e1c3eaf.html" title="Last updated on Mar 2, 2023, 2:45 PM UTC (e1c3eaf)">Diff</a>

Define algorithms for the token store and max batch size.

---

spec.bs

This is a minor cleanup, see diff.
***
<a href="https://pr-preview.s3.amazonaws.com/johannhof/trust-token-api/pull/216.html" title="Last updated on Mar 6, 2023, 11:05 AM UTC (5ba3a15)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/216/dde1cdd...johannhof:5ba3a15.html" title="Last updated on Mar 6, 2023, 11:05 AM UTC (5ba3a15)">Diff</a>

Editorial: Update h4 headers to avoid showing #{ids}

---

spec.bs

Fixes #195.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 6, 2023, 2:24 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FWICG%2Ftrust-token-api%2Fa673ce660de651ae1cd66953b7bd118706788e0d%2Fspec.bs&force=1&md-warning=not%20ready)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server …
```

Add section for issuer fetching/registration.

---

ISSUER_PROTOCOL.md
spec.bs

Fixes #198 and #190.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/208.html" title="Last updated on Mar 7, 2023, 4:15 PM UTC (2201e58)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/208/dde1cdd...2201e58.html" title="Last updated on Mar 7, 2023, 4:15 PM UTC (2201e58)">Diff</a>

Add mask function and integration with crypto.

---

spec.bs

Fixes #202 and #165.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/214.html" title="Last updated on Mar 7, 2023, 5:04 PM UTC (c4fc22e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/214/9d5f665...c4fc22e.html" title="Last updated on Mar 7, 2023, 5:04 PM UTC (c4fc22e)">Diff</a>

Add redeem response handling.

---

spec.bs

Fixes #219
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/220.html" title="Last updated on Mar 16, 2023, 9:22 PM UTC (9b1b0ed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/220/5d89c0a...9b1b0ed.html" title="Last updated on Mar 16, 2023, 9:22 PM UTC (9b1b0ed)">Diff</a>

Remove resolved inline issues

---

spec.bs

Add a section that explains iframe integration.
***
<a href="https://pr-preview.s3.amazonaws.com/aykutbulut/trust-token-api/pull/266.html" title="Last updated on Jul 13, 2023, 7:51 PM UTC (521110d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/266/dffd825...aykutbulut:521110d.html" title="Last updated on Jul 13, 2023, 7:51 PM UTC (521110d)">Diff</a>

Add section on iframe integration

---

spec.bs

#282
***
<a href="https://pr-preview.s3.amazonaws.com/tim-huber/trust-token-api/pull/283.html" title="Last updated on Jan 11, 2024, 4:05 PM UTC (12b437f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/283/eb68759...tim-huber:12b437f.html" title="Last updated on Jan 11, 2024, 4:05 PM UTC (12b437f)">Diff</a>

Reame hasPrivateTokens for consistency with chromium codebase.

---

README.md

Question disguised as a PR: this isn't a "potential api" anymore, it's available now I believe?

Clarify: Current Rather than Future

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/aykutbulut/trust-token-api/pull/302.html" title="Last updated on Jun 18, 2024, 5:47 PM UTC (737819a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/302/cf9ec90...aykutbulut:737819a.html" title="Last updated on Jun 18, 2024, 5:47 PM UTC (737819a)">Diff</a>

add UI guidance on clearing data
