WICG/trust-token-api

README.md
This was confusing, since the heading could be misinterpreted as explaining why the API guarantees privacy, rather than the privacy of the unlinkability property.
Also reworded some of this section to be a bit clearer.
See discussion in the discourse thread for a bit more context:
https://discourse.wicg.io/t/proposal-trust-token-api/3858
=> s/Privacy Guarantee/Cryptographic Property

README.md
Syncing some changes from a local draft:
- a few minor cleanups (in particular, Charlie wanted the brackets around variable names changed to carets after a reader thought the brackets denoted repeated fields)
- clarify meaning of SRR expiry (viz., an expired SRR is treated as if it doesn't exist)
- move the signed-request timestamp into the signing data
- expand the context of the "cross-site information transfer" section slightly
- clarify that number-of-issuers limits apply to issuance from frames, too
=> Syncing changes from local draft

README.md
Two cleanup changes:
- Add the issuance request and response headers' name ("Sec-Trust-Token") to the issuance section.
- Also adds a note that the Sec-Trust-Token request header for redemption can contain things other than just the token that's being redeemed.
=> Restructure redemption section; add name of issuance header

README.md
This change:
- renames the "url" field to "destination" in line with recent changes
- removes the "referer" header from the example as this is one of the headers that it will likely be difficult to sign over (can change on redirects)
=> Update the request signing data example

README.md
This change expands the Future Extensions section to discuss the possibility of obtaining tokens from non-web sources like native applications or operating systems.
=> Add discussion of non-web sources of tokens

README.md
Currently `referer` is not permitted in the singed header list.
`sec-time` header can be included even when includeTimestampHeader is
false, so it can be included in the example.
The current context string is `Trust Token v0` not `Trust-Token-v1`.
=> fix send-srr example and context string

README.md
As mentioned in [#45](https://github.com/WICG/trust-token-api/issues/45#issuecomment-707792652), to support crypto agility for the Request Signing extension we need to provide the algorithm identifier for the algorithm used to sign the request.
=> Add alg field to support crypto agility for Request Signing extension

README.md
Depending on how their ecosystem with RR consumers is configured, issuers may support multiple signing algorithms when signing RRs. In light of this, add a new suggested `SigAlg` field to the sample RR.
=> Add Signing Algorithm as field in Redemption Record sample

ISSUER_PROTOCOL.md, README.md
In V3, we use `ecdsa_secp256r1_sha256` as the signing algorithm for request signing. The key crypto still uses V2, however we bump the dst values.
=> Add protocol version 3 

README.md
Missed adding a link to the signature algorithm source in the README, updating to match the ISSUER_PROTOCOL doc.
=> Add link for ECDSA algorithm

ISSUER_PROTOCOL.md
This allows the key commitment endpoint to support multiple versions and moves 'keys' to be in its own dictionary/namespace.
Fixes #57 and #58.
=> Update key commitment format.

README.md
This closes #81.
Leaves an extension point for more fine-grained clear data behavior in the future.
=> Add token discard header for issuance.

README.md
Currently 'type' is used to refer to Trust Token operation type, i.e., issue or redeem. Possible values are 'token-request' and 'token-redemption'.
I would like to extent current workflow to accommodate operations with other token types and versions for possible extensions that might be desired in the future. For this to work, we need to specify not only the operation type but also the token type. Token type can be specified in a new field in the token operation JSON. Trust token version will be specified in a new field named 'version'.
The complicating part is there is already a 'type' field that specifies the underlying operation type. Options we have are
(1) Keep meaning of 'type' field as is and introduce a new field named
'tokenType' to specify the type of the token.
(2) Re-purpose …
=> Add token type and version

spec.bs
I believe these changes improve readability. Most of the changes are for editors, improving readability in the text editor, but one change is to assist readers in interpreting a period as being a part of the string "Issuing <number of tokens> tokens." rather than a misplaced period in the spec.
=> Minor Improvements to Readability

spec.bs
Added missing links to HTTP headers from normative spec text. 
Fixes #152
=> Add links to HTTP headers

spec.bs
Fixes #153.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/157.html" title="Last updated on Feb 17, 2023, 3:18 PM UTC (cd88039)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/157/5b49140...cd88039.html" title="Last updated on Feb 17, 2023, 3:18 PM UTC (cd88039)">Diff</a>
=> Make batchsize limit implementation-defined.

spec.bs
Mostly moved what was in ISSUER_PROTOCOL.md over to spec.bs, made some minor language changes.
***
<a href="https://pr-preview.s3.amazonaws.com/SamuelSchlesinger/trust-token-api/pull/158.html" title="Last updated on Feb 17, 2023, 3:16 PM UTC (8ad4d13)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/158/9fb6604...SamuelSchlesinger:8ad4d13.html" title="Last updated on Feb 17, 2023, 3:16 PM UTC (8ad4d13)">Diff</a>
=> Added the PMBToken issuance and redemption protocols to spec.bs

spec.bs
This fixes some formatting, since Bikeshed/Markdown doesn't support lettered lists. It also fixes a numbering mismatch, since _I believe_ the bytestring being referred to is `tokens`, which was defined in step 12, not step 11.
***
<a href="https://pr-preview.s3.amazonaws.com/cfredric/trust-token-api/pull/173.html" title="Last updated on Feb 17, 2023, 3:53 PM UTC (7b8c31c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/173/5f1bc15...cfredric:7b8c31c.html" title="Last updated on Feb 17, 2023, 3:53 PM UTC (7b8c31c)">Diff</a>
=> Fix some list numbering/formatting

spec.bs
This fixes #170.
***
<a href="https://pr-preview.s3.amazonaws.com/cfredric/trust-token-api/pull/179.html" title="Last updated on Feb 17, 2023, 4:42 PM UTC (6ee5f6e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/179/0a21f5b...cfredric:6ee5f6e.html" title="Last updated on Feb 17, 2023, 4:42 PM UTC (6ee5f6e)">Diff</a>
=> Specify error types when processing issue responses

spec.bs
This rewrites the `Browser Steps for Issue Response` section in terms of modifications to the Fetch spec.
***
<a href="https://pr-preview.s3.amazonaws.com/cfredric/trust-token-api/pull/186.html" title="Last updated on Feb 17, 2023, 9:34 PM UTC (cf44af6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/186/00b8efd...cfredric:cf44af6.html" title="Last updated on Feb 17, 2023, 9:34 PM UTC (cf44af6)">Diff</a>
=> Rewrite issue response handling via Fetch spec

.github/workflows/auto-publish.yml, spec.bs
- s/browser/user agent
- Fixes a bunch of references
- Clears out some stale issues
- Other small purely editorial changes
- Enables the CI to fail on warnings
***
<a href="https://pr-preview.s3.amazonaws.com/johannhof/trust-token-api/pull/203.html" title="Last updated on Feb 24, 2023, 12:46 PM UTC (3dba1c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/203/7f49956...johannhof:3dba1c9.html" title="Last updated on Feb 24, 2023, 12:46 PM UTC (3dba1c9)">Diff</a>
=> Various editorial improvements, fail CI on warnings.

spec.bs
Add version field in PrivateStateToken  dictionary. Fixes #136.
***
<a href="https://pr-preview.s3.amazonaws.com/aykutbulut/trust-token-api/pull/209.html" title="Last updated on Mar 9, 2023, 4:33 AM UTC (ba74165)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/209/4359cfb...aykutbulut:ba74165.html" title="Last updated on Mar 9, 2023, 4:33 AM UTC (ba74165)">Diff</a>
=> Add version field in PrivateStateToken  dictionary

spec.bs
In spec current main branch, version refers to the underlying PST crypto protocol version. Make this explicit in text, algorithms and http headers. Fixes #188
***
<a href="https://pr-preview.s3.amazonaws.com/aykutbulut/trust-token-api/pull/217.html" title="Last updated on Mar 10, 2023, 1:55 PM UTC (9139f44)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/217/1fadee9...aykutbulut:9139f44.html" title="Last updated on Mar 10, 2023, 1:55 PM UTC (9139f44)">Diff</a>
=> Define crypto protocol version

spec.bs
Changed expirion to expiration, seems like it was a typo. Is data meant to be date as well?
***
<a href="https://pr-preview.s3.amazonaws.com/SamuelSchlesinger/trust-token-api/pull/234.html" title="Last updated on Apr 16, 2023, 11:58 AM UTC (108e278)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/234/f9a0507...SamuelSchlesinger:108e278.html" title="Last updated on Apr 16, 2023, 11:58 AM UTC (108e278)">Diff</a>
=> Changed expirion to expiration

README.md, spec.bs
Given the lack of strong support for this functionality, and concerns raising in #231, we are currently planning on removing support for this variant in the initial version of the API.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/236.html" title="Last updated on Apr 19, 2023, 2:11 PM UTC (b544d8c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/236/9594b66...b544d8c.html" title="Last updated on Apr 19, 2023, 2:11 PM UTC (b544d8c)">Diff</a>
=> Remove Private Metadata variant from web-exposed API.

spec.bs
This removes "type" from the API until it is needed, resolving #222 and reducing the versioning to "version" to resolve #224.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/241.html" title="Last updated on May 3, 2023, 1:46 PM UTC (8572ed6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/241/43a56f6...8572ed6.html" title="Last updated on May 3, 2023, 1:46 PM UTC (8572ed6)">Diff</a>
=> Remove "type" from API.

spec.bs
Add permission policy feature definitions. 
Update the Request constructor with policy checks in Modifications to request section.
***
<a href="https://pr-preview.s3.amazonaws.com/aykutbulut/trust-token-api/pull/239.html" title="Last updated on May 8, 2023, 6:12 PM UTC (9916391)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/239/9927f3c...aykutbulut:9916391.html" title="Last updated on May 8, 2023, 6:12 PM UTC (9916391)">Diff</a>
=> Add permission policy checks

ISSUER_PROTOCOL.md, spec.bs
This fixes #232.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/247.html" title="Last updated on May 18, 2023, 8:34 PM UTC (17e4289)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/247/c078408...17e4289.html" title="Last updated on May 18, 2023, 8:34 PM UTC (17e4289)">Diff</a>
=> Add media type for key commitments.

spec.bs
Refer to right request in "set private token properties for request" algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/aykutbulut/trust-token-api/pull/267.html" title="Last updated on Jul 12, 2023, 2:19 AM UTC (1779d18)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/267/eb68759...aykutbulut:1779d18.html" title="Last updated on Jul 12, 2023, 2:19 AM UTC (1779d18)">Diff</a>
=> Refer to right request

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/tim-huber/trust-token-api/pull/265.html" title="Last updated on Jul 13, 2023, 2:22 PM UTC (38dc865)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/265/bbf62cd...tim-huber:38dc865.html" title="Last updated on Jul 13, 2023, 2:22 PM UTC (38dc865)">Diff</a>
=> first attempt at XHR spec update

spec.bs
Use "Should request be allowed to use feature?" algorithm instead of "Is feature enabled in document for origin?". The former requires only a policy feature and a request. This simplifies things.
Change the order of the arguments for "set private token properties for request from private token" in XHR section.
Fixes #269.
***
<a href="https://pr-preview.s3.amazonaws.com/aykutbulut/trust-token-api/pull/270.html" title="Last updated on Jul 13, 2023, 7:47 PM UTC (7dd9350)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/270/1756871...aykutbulut:7dd9350.html" title="Last updated on Jul 13, 2023, 7:47 PM UTC (7dd9350)">Diff</a>
=> Update permission policy check

spec.bs
PR #266 introduced the `privateToken` attribute on `iframe`. The attribute was flagged with a `Reflect` extended attribute to indicate that it reflects the `privateToken` content attribute (already specified in prose). While this attribute is understood by some browser code bases, it is not a standard one, and not defined Web IDL in particular.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/trust-token-api/pull/271.html" title="Last updated on Jul 14, 2023, 7:07 AM UTC (ef5e0b1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/271/6596d23...tidoust:ef5e0b1.html" title="Last updated on Jul 14, 2023, 7:07 AM UTC (ef5e0b1)">Diff</a>
=> Drop non-standard "Reflect" extended attribute

README.md
Based on feedback and the complexities of supporting non-web sources of tokens, this API is probably not the right shape for supporting those types of tokens (and they are better suited to an alternative privacypass API).
=> Remove non-web sources.

spec.bs
Fix key commitment field explanations. Fixes #279
***
<a href="https://pr-preview.s3.amazonaws.com/aykutbulut/trust-token-api/pull/280.html" title="Last updated on Dec 28, 2023, 2:58 PM UTC (db228c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/280/1466b7d...aykutbulut:db228c0.html" title="Last updated on Dec 28, 2023, 2:58 PM UTC (db228c0)">Diff</a>
=> Fix key commitment field explanations

spec.bs
In the current implementation, we don't diverge from the batched spec and don't include the blinded element in the IssueResponse.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/pull/295.html" title="Last updated on Mar 27, 2024, 4:08 PM UTC (db917ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/295/cb60720...db917ec.html" title="Last updated on Mar 27, 2024, 4:08 PM UTC (db917ec)">Diff</a>
=> Remove incorrect field from IssueResponse.

README.md
Update fetch API in the explainer to the shipped
version of the Private State Tokens.
=> Update fetch API in explainer

spec.bs
Replaced redemptionTimes map with redemptionRecords.
***
<a href="https://pr-preview.s3.amazonaws.com/cooleck/trust-token-api/pull/300.html" title="Last updated on Jun 8, 2024, 2:36 PM UTC (4c6ca08)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/300/00dd7af...cooleck:4c6ca08.html" title="Last updated on Jun 8, 2024, 2:36 PM UTC (4c6ca08)">Diff</a>
=> Corrected a tipo in retrieve redemption record algorithm.

README.md, spec.bs
To ensure the issuers the top-level site wants are preserved for use, calling hasPrivateToken up to twice will reserve the two slots for allowed issuers.
***
<a href="https://pr-preview.s3.amazonaws.com/arichiv/trust-token-api/pull/305.html" title="Last updated on Jul 18, 2024, 11:51 AM UTC (344d11f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/trust-token-api/305/ae07cb5...arichiv:344d11f.html" title="Last updated on Jul 18, 2024, 11:51 AM UTC (344d11f)">Diff</a>
=> Preventing Issuer Exhaustion
